// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package comment

import (
	"coderblog-interface/api/comment"
)

type ControllerV1 struct{}

func NewV1() comment.ICommentV1 {
	return &ControllerV1{}
}
