server:
  address:     ":8080"
  openapiPath: "/api.json"
  serverRoot: "/resource"

logger:
  path:  "./log/lionblog_pro"
  level : "all"
  stdout: true

database:
  logger:
    path:  "./log/lionblog_pro/sql"
    level: "all"
    stdout: true

  default:
    link: "mysql:root:ilovecoding.@tcp(mysql:3307)/lionblog_production?loc=Local&parseTime=true"
    debug: true



