// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package notebook

import (
	"coderblog-interface/api/notebook"
)

type ControllerAdminV1 struct{}

func NewAdminV1() notebook.INotebookAdminV1 {
	return &ControllerAdminV1{}
}

type ControllerV1 struct{}

func NewV1() notebook.INotebookV1 {
	return &ControllerV1{}
}
