// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package menu

import (
	"coderblog-interface/api/menu"
)

type ControllerV1 struct{}

func NewV1() menu.IMenuV1 {
	return &ControllerV1{}
}
