// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package article

import (
	"coderblog-interface/api/article"
)

type ControllerV1 struct{}

func NewV1() article.IArticleV1 {
	return &ControllerV1{}
}
