// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package banner

import (
	"coderblog-interface/api/banner"
)

type ControllerV1 struct{}

func NewV1() banner.IBannerV1 {
	return &ControllerV1{}
}
