// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"coderblog-interface/internal/dao/internal"
)

// internalArticleCommentDao is internal type for wrapping internal DAO implements.
type internalArticleCommentDao = *internal.ArticleCommentDao

// articleCommentDao is the data access object for table article_comment.
// You can define custom methods on it to extend its functionality as you wish.
type articleCommentDao struct {
	internalArticleCommentDao
}

var (
	// ArticleComment is globally public accessible object for table article_comment operations.
	ArticleComment = articleCommentDao{
		internal.NewArticleCommentDao(),
	}
)

// Fill with you ideas below.
