// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"coderblog-interface/internal/dao/internal"
)

// internalBannerDao is internal type for wrapping internal DAO implements.
type internalBannerDao = *internal.BannerDao

// bannerDao is the data access object for table banner.
// You can define custom methods on it to extend its functionality as you wish.
type bannerDao struct {
	internalBannerDao
}

var (
	// Banner is globally public accessible object for table banner operations.
	Banner = bannerDao{
		internal.NewBannerDao(),
	}
)

// Fill with you ideas below.
