// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"coderblog-interface/internal/dao/internal"
)

// internalMenuRoleDao is internal type for wrapping internal DAO implements.
type internalMenuRoleDao = *internal.MenuRoleDao

// menuRoleDao is the data access object for table menu_role.
// You can define custom methods on it to extend its functionality as you wish.
type menuRoleDao struct {
	internalMenuRoleDao
}

var (
	// MenuRole is globally public accessible object for table menu_role operations.
	MenuRole = menuRoleDao{
		internal.NewMenuRoleDao(),
	}
)

// Fill with you ideas below.
