// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"coderblog-interface/internal/dao/internal"
)

// internalNotebookDao is internal type for wrapping internal DAO implements.
type internalNotebookDao = *internal.NotebookDao

// notebookDao is the data access object for table notebook.
// You can define custom methods on it to extend its functionality as you wish.
type notebookDao struct {
	internalNotebookDao
}

var (
	// Notebook is globally public accessible object for table notebook operations.
	Notebook = notebookDao{
		internal.NewNotebookDao(),
	}
)

// Fill with you ideas below.
