// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"coderblog-interface/internal/dao/internal"
)

// internalNotebookCommentDao is internal type for wrapping internal DAO implements.
type internalNotebookCommentDao = *internal.NotebookCommentDao

// notebookCommentDao is the data access object for table notebook_comment.
// You can define custom methods on it to extend its functionality as you wish.
type notebookCommentDao struct {
	internalNotebookCommentDao
}

var (
	// NotebookComment is globally public accessible object for table notebook_comment operations.
	NotebookComment = notebookCommentDao{
		internal.NewNotebookCommentDao(),
	}
)

// Fill with you ideas below.
