// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"coderblog-interface/internal/dao/internal"
)

// internalUserRoleDao is internal type for wrapping internal DAO implements.
type internalUserRoleDao = *internal.UserRoleDao

// userRoleDao is the data access object for table user_role.
// You can define custom methods on it to extend its functionality as you wish.
type userRoleDao struct {
	internalUserRoleDao
}

var (
	// UserRole is globally public accessible object for table user_role operations.
	UserRole = userRoleDao{
		internal.NewUserRoleDao(),
	}
)

// Fill with you ideas below.
