// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package upload

import (
	"coderblog-interface/api/upload"
)

type ControllerAdminV1 struct{}

func NewAdminV1() upload.IUploadAdminV1 {
	return &ControllerAdminV1{}
}
